<?php
    /**
     * Created by PhpStorm.
     * User: Digby
     * Date: 19/09/2017
     * Time: 8:07 AM
     */

    /*
     * HTML that should be included on every page on the site
     * */

    echo "
    <!DOCTYPE html>
    <html lang='en'>
    <head>
    
    <meta charset='utf-8' />
    
    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">

	<!-- Setting the width -->
	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">

	<title>View Posts</title>

	<!-- Bootstrap CSS -->
	<link href=\"css/bootstrap.css\" rel=\"stylesheet\">

	<!-- CSS -->
	<link href=\"css/main.css\" rel=\"stylesheet\">
	<script src=\"js/postjs.js\"></script>
    
    ";