<?php
    /**
     * Created by PhpStorm.
     * User: Digby
     * Date: 19/09/2017
     * Time: 8:07 AM
     */

    /*
     * HTML that should be included on every page on the site
     * */

    echo "
    <!DOCTYPE html>
    <html lang='en'>
    <head>
    <meta charset='utf-8' />
    <link href='./css/mainStyles.css' type='text/css' rel='stylesheet' />
    <script type='text/javascript' src='./js/script.js'></script>
    ";