<?php
    /**
     * Created by PhpStorm.
     * User: Digby
     * Date: 19/09/2017
     * Time: 8:07 AM
     */

    /*
     * HTML that should be included on every page on the site
     * */

    echo "
    <!DOCTYPE html>
    <html lang='en'>
    <head>
    
    <meta charset='utf-8' />
    
    <link href='./css/mainStyles.css' type='text/css' rel='stylesheet' />
    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>
    <script type='text/javascript' src='./js/script.js'></script>
    <meta charset='utf-8'>
	<meta http-equiv='X-UA-Compatible' content='IE=edge'>

	<!-- Setting the width -->
	<meta name='viewport' content='width=device-width, initial-scale=1.0'>

	<title>Welcome to TeachHub</title>

	<!-- Bootstrap CSS -->
	<link href='css/bootstrap.css' rel='stylesheet'>

	<!-- CSS -->
	<link href='css/main.css' rel='stylesheet'>
	
	<!-- jquery -->
	<script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
</head>";