<?php
/**
 * Created by PhpStorm.
 * User: Digby
 * Date: 27-Sep-17
 * Time: 10:36 AM
 */

/*
 * Main navigation bar along the top (?) of each page.
 *
 * */

echo "<nav class='mainNavigation'>";
echo "<ul>";

echo "<li><a href='https://lornasfanbois.uqcloud.net/'>Home</a></li>";
echo "<li><a href='../post.php'>Posts</a></li>";
echo "<li><a href='#'>Item3</a></li>";
echo "<li><a href='#'>My account</a></li>";
echo "<li><a href='#'>About</a></li>";

echo "</ul>";
echo "<button title='New post' id='newPostButton'>+</button>";
echo "</nav>";